name: UI Test with Playwright & Allure

# 触发条件：push 或 pull request 到 main 分支
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Python
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3. 安装依赖
      # --with-deps：安装浏览器及依赖
      # ghp-import： 用于推送到 GitHub Pages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      # 4. 安装 Allure CLI
      # 用于执行命令allure generate
      - name: Install Allure CLI
        run: |
          # 下载最新版本
          ALLURE_VERSION=2.27.0
          wget https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.tgz
          tar -zxvf allure-$ALLURE_VERSION.tgz
          sudo mv allure-$ALLURE_VERSION /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version
          
      # 5. 运行测试并生成 Allure 原始数据
      # --alluredir=allure-results：生成原始测试数据
      - name: Run tests with Allure
        continue-on-error: true  # ❗ 确保失败也继续执行后续步骤
        run: |
          pytest --alluredir=allure-results

      # 6. 生成 Allure HTML 报告
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      # 7. 上传 Allure HTML 报告作为 Artifact
      - name: Upload Allure Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
      # 将artifacts下trace.zip拷贝到Actions->artifacts中
      - name: Copy trace into allure report
        if: always()
        run: |
          mkdir -p allure-report/trace
          cp artifacts/**/trace.zip allure-report/trace/ || true
          
      # 8. 部署 Allure HTML 报告到 GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
